richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/XMLEditor.java
richtextfx-demos/src/main/resources/org/fxmisc/richtext/demo/xml-highlighting.css

Hi Tomas,
I closed the previous pull request because I found a bug in my demo. This one is working ok, now.
Here is my pull request with an XMLEditor demo. I thought the poor man's regex parsing method was still the best (I tried with stax, but found it difficult to get the cursor positions on attributes).
I think it might not be very performant with large xml files, since it calls for a full text parsing on every keystroke. Any ideas how I can make this better?
Kind regards
Carlos

Xml editor demo

---

richtextfx/src/main/java/org/fxmisc/richtext/skin/ParagraphText.java
richtextfx/src/main/java/org/fxmisc/richtext/skin/TextExt.java

Just as you suggested the implementation is based on the same principles as the selection fill.
On top of that I had to extend Text to support CSS based colors.
I should mention that I have only implemented -fx-background-color and not anything else from -fx-background. JavaFX under the hood is so damn weird that it would be rather ugly to support the actual Background property. Using just the color property makes the code simple and shouldn't have a huge impact like having an actual Image in every Text instance.
One thing I would like to improve is the background node instantiation. Right now every Text instance has a matching background Path. Maybe it is possible to create only Path instances when there actually is a background color set.
Well I'm actually quite happy with the result. …

Implemented background colors for text

---

richtextfx/src/main/java/org/fxmisc/richtext/NavigationActions.java
richtextfx/src/main/java/org/fxmisc/richtext/skin/StyledTextAreaBehavior.java

Turns out I wrote this on top of the branch I used for exposing the scroll API. Do you want me to create a separate branch without the exposure and create a PR ? Not sure what best practices are in this regard.

Selection Fix

---

richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java

I'm removing the TODO reminder as its irrelevant.
It looks like we missed the VIrtualizedScrollPane component that shouldn't be apart of this anymore. So, I'm removing that before anything else gets done.

Remove TODO reminder and last remnants of VirtualizedScrollPane

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/CloneDemo.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/RichText.java
richtextfx/src/main/java/org/fxmisc/richtext/AreaFactory.java
richtextfx/src/main/java/org/fxmisc/richtext/CodeArea.java
richtextfx/src/main/java/org/fxmisc/richtext/EditableStyledDocument.java
richtextfx/src/main/java/org/fxmisc/richtext/InlineCssTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/InlineStyleTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyleClassedTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java

This is the same result of the #231 but with a cleaner commit history.

2+ Views (areas) share the same Model (document)

---

richtextfx/src/main/java/org/fxmisc/richtext/AreaFactory.java
richtextfx/src/main/java/org/fxmisc/richtext/CssProperties.java
richtextfx/src/main/java/org/fxmisc/richtext/EditableStyledDocument.java
richtextfx/src/main/java/org/fxmisc/richtext/InlineCssTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
richtextfx/src/main/java/org/fxmisc/richtext/StyleClassedTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyleSpans.java
richtextfx/src/main/java/org/fxmisc/richtext/StyleSpansBuilder.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledDocumentBase.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledText.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextAreaModel.java

- Replace "(arg1, arg2) -> arg1.method(arg2)" lambdas with method references
- Removed explicit type since it can be inferred (e.g. "<PS, S>" --> "<>")
- Removed unneeded semi-colons
- Removed unused Type parameter "<C>"
- Removed `initialParagraphStyle` from `createCell()` since it isn't used there.
- Made `omniSuspendable` a local variable since suspending EditableStyledDocument's `beingUpdatedProperty()` suspends all clones' Suspendables now instead of `omniSuspendable`

Minor code refactoring to get rid of some compiler suggestions:

---

richtextfx/src/main/java/org/fxmisc/richtext/AreaFactory.java
richtextfx/src/main/java/org/fxmisc/richtext/CodeArea.java
richtextfx/src/main/java/org/fxmisc/richtext/EditableStyledDocument.java
richtextfx/src/main/java/org/fxmisc/richtext/EditableStyledDocumentImpl.java
richtextfx/src/main/java/org/fxmisc/richtext/InlineCssTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyleClassedTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextAreaModel.java
richtextfx/src/test/java/org/fxmisc/richtext/EditableStyledDocumentImplTest.java
richtextfx/src/test/java/org/fxmisc/richtext/StyledTextAreaModelTest.java

I used `EditableStyledDocument`'s methods as the base for the new interface.

Custom EditableStyledDocument

---

richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java

I wasn't sure what to put for the parameter description. However, I thought the example given in the javadoc would explain any further questions developers might have. So, I'm guessing it's ok to not describe the parameters.

Remove javadoc for x, y params to get rid of warnings

---

richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java

I have run into issue #144 (to make the caret visible on non-editable controls), and also I wish to be able to configure the rate of blinking.  (Some users must disable blinking cursors for accessibility reasons, so to hardcode the blink rate is problematic.)
So I have attempted to modify StyledTextArea to make this behavior customisable.  This seems to be working well in my application, but I would rather not maintain my own branch forever :)
I don't know whether you will agree with the implementation, as this is the first time I tried to write code using ReactFX, so I would appreciate your comments if there is a better way to do this!  Also I have not tried to expose these options in CSS, although perhaps that should be done?

Allow customisation of caret visibility criteria and blink rate.

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/lineindicator/ArrowFactory.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/lineindicator/LineIndicatorDemo.java

Extracted this demo from Tomas' StackOverflow answer
Since you mentioned it in #360, I thought it would be trivial to do and very helpful for others to have.

Demonstrate via demo the usage of StyledTextArea#paragraphGraphicFactory

---

richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java

This should fix #128's second problem (the previous PR had a weird commit history issue).

Relayout popup when any of its settings are invalidated

---

richtextfx/src/main/java/org/fxmisc/richtext/StyledTextAreaBehavior.java

Handle drag events only if mouse release occurred inside of view

---

richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextAreaBehavior.java

Is `StyledTextAreaBehavior#TargetCaretOffset` even needed after this (line 220)?

Expose API for page up/down

---

richtextfx/src/main/java/org/fxmisc/richtext/StyledTextAreaBehavior.java

This fixes #200. I could write a test for it, but that would require adding a TestFX test dependency in headless mode so that the travis build still works correctly.

(Shift) + Shortcut + Left/Right skips only 1 word boundary, not 2

---

richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextAreaBehavior.java

Should fix #101, but I'm not sure if I implemented it correctly.

Request follow caret

---

richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java

Make `requestFollowCaret` public and wrote its javadoc

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java

This PR fixes computing hit character (at mouse press) if padding is set on the paragraph-text.
To reproduce this, apply a large padding (as below), click at some text in the styled text area and see where the caret is positioned. Without this fix the caret is always some characters right to the click location.
```
.styled-text-area .paragraph-box .paragraph-text {
-fx-padding: 0 10em 0 10em;
}
.styled-text-area .paragraph-box:first-paragraph .paragraph-text {
-fx-padding: 10em 10em 0 10em;
}
.styled-text-area .paragraph-box:last-paragraph .paragraph-text {
-fx-padding: 0 10em 10em 10em;
}
```

Fix computing hit character if padding is set on the paragraph-text

---

richtextfx/src/main/java/org/fxmisc/richtext/LineNumberFactory.java

This was a small issue that was overlooked in #356. I only came across it due to examining the code due to some other issue.

Update type to be the new base area type

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Expose API for "scroll[x/y]By(delta)"

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/model/StyledTextAreaModel.java
richtextfx/src/main/java/org/fxmisc/richtext/model/TextEditingArea.java

Since this may have value beyond what I know for code editors and the like, I have to ask: why did you originally implement this method? Is making this method package private desirable? AFAIK, we're only doing that because many confused `moveTo`'s functionality for `positionCaret`, since the latter implies that more so than the former.
In my opinion, it would be better to rename `moveTo` to include "caret" in it (`moveCaretTo`? `moveCaret`? `caretTo`?) and rename `positionCaret` to include more explanatory details (`positionCaretDisconnectedly`? `positionCaretSeparately`?).

Make `positionCaret` package-private

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Reimplementation of #349 but on the current master branch. This PR differs only in that it includes javadoc for the method.

Add API: get # of lines a wrapped paragraph spans

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextAreaBehavior.java
richtextfx/src/main/java/org/fxmisc/richtext/TextFlowExt.java
richtextfx/src/main/java/org/fxmisc/richtext/model/NavigationActions.java

> The methods lineStart and lineEnd move the cursor to the start and end of the paragraph, not the line. Their names should be changed to paragraphStart and paragraphEnd to avoid confusion, as well as renaming selectLine to selectParagraph.
> When pressing either Home or End, the caret position should change relative to the current line, not the current paragraph, which is what users have come to expect (e.g., the text area used to write this message has typical home/end key behaviour). There are a few related issues: #384 and #360.

Update method & behavior: lineStart/End, not paragraphStart/End

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/PopupDemo.java
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
richtextfx/src/main/java/org/fxmisc/richtext/PopupAlignment.java

I encountered an issue with calling `getCaretBounds` and `getSelectionBounds` near the same time when using EventStreams.

Deprecate Popup API; add caret/selection bounds properties

---

README.md

Fix dead link to manual download of 0.7-M3 release

---

richtextfx/build.gradle

- Note: current Flowless version in use is 0.5.1, but updating to that link did not work.

Resolve javadoc links to Flowless (0.5.0)

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/EmptyLinkedImage.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/LinkedImage.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/LinkedImageOps.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/RealLinkedImage.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/RichText.java

I think turning `LinkedImage` into an interface with an empty and non-empty classes better shows how one should implement a custom object. It cleans up the code logic in what's now called `RealLinkedImage` due to no longer accounting for the possibility of it being the empty version.

Update custom object example to use interface

---

richtextfx/build.gradle
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextAreaBehavior.java
richtextfx/src/test/java/org/fxmisc/richtext/model/StyledTextAreaBehaviorTest.java

This addresses #363.
There is no `ContextMenu` by default: this matches the same behavior as all other nodes.
- Should the default offset values be `5` or some positive non-zero value? In the TestFX test, having it as zero will fail the tests because the mouse clicks on the menu rather than the area once it is shown. Developer who set the menu in their code will also need to override the default values every time, which is unnecessary boilerplate.
- **Edit:** I've updated the PR to set the default offset values to `2`. There's no specific reason for this choice, so it's up for modification.

Add context menu

---

richtextfx/src/test/java/org/fxmisc/richtext/model/StyledTextAreaBehaviorTest.java

Addresses #454 
On another note, the test should be using `push` rather than `press` as the former releases the key whereas the latter simply holds it down until the test ends.

Ignore test due to TestFX issue (should re-enable when fixed)

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

A few questions I have:
- Should `selectionShape` be used to get the bounds? Will that switch-out approach cause any issues later on? I didn't want to create a new `Path` object each time the method is called so as to reduce memory usage.
- I used the `FORWARD` bias in `endPosition = offsetToPosition(to, Bias.FORWARD)`. Is that correct? Or should it be `BACKWARD`? I still don't understand how that part of the code works.

Add feature: get character bounds on screen

---

richtextfx/src/main/java/org/fxmisc/richtext/CodeArea.java
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/InlineCssTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyleClassedTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java

Make areas FXML ready via "@NamedArg(parameterName)"

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextAreaBehavior.java
richtextfx/src/main/java/org/fxmisc/richtext/ViewActions.java
richtextfx/src/main/java/org/fxmisc/richtext/model/NavigationActions.java
richtextfx/src/test/java/org/fxmisc/richtext/model/InlineCssTextAreaAppTest.java
richtextfx/src/test/java/org/fxmisc/richtext/model/StyledTextAreaBehaviorTest.java

I'm not going to merge this just yet. I'm going to write some TestFX tests that simulates the expected behavior of the mouse behavior before this PR's changes were added to it. Then I'll rebase the work here (and clean it up) to insure that the new code works exactly as the previous code.

Split up mouse handling so that overriding default mouse behavior does not affect other default behavior

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/model/GenericEditableStyledDocumentBase.java
richtextfx/src/test/java/org/fxmisc/richtext/model/StyledTextAreaBehaviorTest.java

Turns out I didn't copy this code over into the view correctly because it mixed model and view API calls together

Fix regression: Update caret position after replace call

---

richtextfx/src/main/java/org/fxmisc/richtext/TextExt.java
richtextfx/src/main/java/org/fxmisc/richtext/model/Paragraph.java
richtextfx/src/main/java/org/fxmisc/richtext/model/StyledText.java
richtextfx/src/main/java/org/fxmisc/richtext/model/TwoDimensional.java

I tried to document everything where I was confident about how it worked, so a few methods in these classes are still uncommented.  But thought it might prove useful in improving the Javadoc a bit, even if some of the content is already on the wiki.

Added some documentation to some small classes

---

richtextfx/src/main/java/org/fxmisc/richtext/model/PlainTextChange.java
richtextfx/src/main/java/org/fxmisc/richtext/model/RichTextChange.java
richtextfx/src/main/java/org/fxmisc/richtext/model/TextChange.java

Fixes regressions introduced by #458 by implementing the changes proposed in #486.

Limit TextChange's type's possibilities by only using it for merging

---

richtextfx/src/main/java/org/fxmisc/richtext/LineNumberFactory.java

Fixed line numbers alignment and changed default padding to spaces as discussed in #488
Before:
After:

Fix line numbers alignment and change default padding to spaces. #488

---

richtextfx/src/main/java/org/fxmisc/richtext/model/TextChange.java

Reverts back to the previous merge method

Revert to previous merge method

---

richtextfx/src/test/java/org/fxmisc/richtext/model/InlineCssTextAreaAppTest.java
richtextfx/src/test/java/org/fxmisc/richtext/model/StyledTextAreaBehaviorTest.java

I noticed that the mouse moves from the center of the area (due to `clickOn(area)`) to the top left portion of the first line and vice versa a couple of times in the test. This causes the test suite to take longer than necessary.
`gradle test` on my machine (I ran `gradle clean` before running the tests):
Before | After (in seconds)
18.975 | 15.514

Speed up test fx tests

---

richtextfx/src/main/java/org/fxmisc/richtext/model/Paragraph.java
richtextfx/src/main/java/org/fxmisc/richtext/model/StyleSpansBuilder.java
richtextfx/src/test/java/org/fxmisc/richtext/model/ParagraphTest.java

Fix style spans issue

---

.travis.yml

re-adds the debug flag to travis so we can see why tests fail. In particular, which test in the `integrationTest` suite fails and why (time out?).

Add debug flag to Travis build

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/keyboard/CutCopyPasteTests.java
richtextfx/src/integrationTest/java/org/fxmisc/richtext/view/MiscellaneousAPITests.java
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Account for insets in `layoutChildren()`

---

build.gradle
richtextfx-demos/build.gradle
richtextfx/build.gradle

Manifest files were added to the RichTextFX libraries. Implementation and specification version were set to 0.7.0-M6 and 0.7.0 respectively. See http://semver.org.
Note that the version information must be updated manually. They also might be derived from Git tags
using Gradle plugins like https://github.com/palantir/gradle-git-version.

Fix issue 476

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/ViewActions.java

I feel like this should be suspended somewhere...

Expose visible paragraphs

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/keyboard/NavigationTests.java
richtextfx/src/integrationTest/java/org/fxmisc/richtext/view/MiscellaneousAPITests.java
richtextfx/src/main/java/org/fxmisc/richtext/BoundedSelection.java
richtextfx/src/main/java/org/fxmisc/richtext/BoundedSelectionImpl.java
richtextfx/src/main/java/org/fxmisc/richtext/Caret.java
richtextfx/src/main/java/org/fxmisc/richtext/CaretImpl.java
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
richtextfx/src/main/java/org/fxmisc/richtext/UnboundedSelection.java
richtextfx/src/main/java/org/fxmisc/richtext/UnboundedSelectionImpl.java
richtextfx/src/main/java/org/fxmisc/richtext/ViewActions.java
richtextfx/src/main/java/org/fxmisc/richtext/model/TextEditingArea.java

Extract caret and selection to separate classes

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/model/UndoActions.java
richtextfx/src/main/java/org/fxmisc/richtext/util/UndoUtils.java

Addresses #333 
One cannot pass in an `UndoManager` as an argument since its `apply` Consumer requires the area to already be constructed. As such, the area still constructs the default `UndoManager`. However, once the area is constructed, this PR now allows one to set the area's undoManager directly and not indirectly through an `UndoManagerFactory`. 
Thus, one has complete control over how the `UndoManager` is constructed and functions. It could only handle changes to the area's text, only changes to the area's view, or something else altogether.
Future PRs could add other factory methods for constructing `UndoManager`s that work differently.

Allow UndoManager to use developer-defined changes (text, view, etc.)

---

richtextfx/src/main/java/org/fxmisc/richtext/BoundedSelection.java
richtextfx/src/main/java/org/fxmisc/richtext/BoundedSelectionImpl.java
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/UnboundedSelectionImpl.java
richtextfx/src/main/java/org/fxmisc/richtext/util/UndoUtils.java

- Reposition a few things
- Fixes a few minor mistakes in #526 (Makes the Selection interfaces' implementations final and package-private)
- Clean up UndoUtils and add javadoc from #528.

Reposition code and refactor / add javadoc to #526 & #528

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/view/MiscellaneousAPITests.java
richtextfx/src/integrationTest/java/org/fxmisc/richtext/view/UndoManagerTests.java
richtextfx/src/main/java/org/fxmisc/richtext/util/UndoManagerInactivityWrapper.java
richtextfx/src/main/java/org/fxmisc/richtext/util/UndoUtils.java

Addresses #362.
This should really be changed in UndoFX. But since that won't have a new release in the foreseeable future, this can bring the same functionality until such a release exists.

Stop next change from merging with previous one after inactive period.

---

README.md

Jitpack to readme

---

README.md

We've just released the latest version of BlueJ, which now uses RichTextFX.   BlueJ is an educational IDE for Java. We have in the order of 300,000 users a month, so RichTextFX will be in use by a lot of people.
Just wanted to say thanks for the library: we used to use Swing's JEditorPane, but for various reasons (HiDPI support, SwingNode bugs) we needed to transition to JavaFX.  We had previously held off because there was no good in-built JavaFX component for text editing, so finding RichTextFX was a real bonus for us.  It was flexible enough that we were able to bend it to do what we needed, including our scope highlighting (see below).  So: thanks!
Here's a shot of our RichTextFX-backed editor:

Added BlueJ to the list of projects using RichTextFX

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/HitTests.java
richtextfx/src/integrationTest/resources/org/fxmisc/richtext/api/padded-paragraph-box.css
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java

Account for padding in ParagraphBox's layout call

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Removes unused methods/imports
Fixes a bug: area's target caret offset value is used instead of the main caret's one.

Remove unused method/import; use caret's target caret offset, not area's

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/LinkedImageOps.java
richtextfx/src/main/java/org/fxmisc/richtext/model/NodeSegmentOpsBase.java
richtextfx/src/main/java/org/fxmisc/richtext/model/SegmentOpsBase.java

Reduces boilerplate and properly implements the `SegmentOps` interface using the pattern described in the Wiki.

Easier custom object support

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

Only construct background/underline shapes when needed

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
richtextfx/src/main/java/org/fxmisc/richtext/TextFlowExt.java

Only uses 1 shape for a value (background, underline) shared between multiple consecutive TextExt segments.
This provides the needed support to quickly implement #346 without the adjacent segments issue.

Optimize background color and underline shapes

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

Resolves #549 according to the IntelliJ style
Note: this PR should be refactored because `getParagraphSelection` now returns `IndexRange(start, paragraph.length() + 1)` in some cases.
I'd like to say that there should be two separate methods: one for getting just the range inside the paragraph and another that adds one if it includes the newline character.

Enhancement: Selecting a newline char selects the rest of the line

---

richtextfx/src/main/java/org/fxmisc/richtext/model/Paragraph.java
richtextfx/src/main/java/org/fxmisc/richtext/model/StyledText.java

Fix either ops bug

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink/Hyperlink.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink/HyperlinkDemo.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink/HyperlinkOps.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink/TextHyperlinkArea.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink/TextStyle.java
richtextfx-demos/src/main/resources/org/fxmisc/richtext/demo/hyperlink/text-hyperlink-area.css

Shows custom object support in a less-cluttered way than the RichTextDemo.

Add Hyperlink demo - minimum needed for custom object integration

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/keyboard/NavigationTests.java
richtextfx/src/main/java/org/fxmisc/richtext/TextFlowExt.java

This PR fixes some issues with caret positioning in **wrapped lines**:
1) pressing `DOWN` key at end of line now moves caret to end of next line (and not beginning of line after next line).
E.g. if caret is at `|` then `DOWN` key moves it to `^` (and not `*` as before).
~~~
01234|
678^
*01
~~~
2) `UP` key now always works as expected (and no longer "locks" at `*` as before)
3) when clicking with the mouse after text in a wrapped line (e.g. right to `^`), then the caret is now positioned at the end of the hit line (and not at the beginning of the next line as before)
Here is some code to reproduce:
~~~java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.fxmisc.flowless.VirtualizedScrollPane;
import …

fixed caret positioning in wrapped lines (issue #423)

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

It the text area displays line numbers, then the selection of empty lines is not displayed correctly.
This PR fixes this.

fix selection painting of empty lines if text area displays line numbers

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

Adjust right edge of wrapped lines selection to the rest of the line (similar to #549 / #564). IOW when selection the space character at the end of a wrapped line, then the selection is expanded to the right edge of the text area.
Old:
("01234 678 01" is a single line)
New:
Also closed rectangle path in `ParagraphText.createRectangle()`. Not sure whether this makes any difference, but `com.sun.javafx.text.PrismTextLayout.getRange()` does it too. So there might be a reason...

adjust wrapped lines selection to the rest of the line

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/MiscellaneousTests.java
richtextfx/src/main/java/org/fxmisc/richtext/SelectionImpl.java

Use old approach to update selection's 2D positions

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/mouse/ClickAndDragTests.java
richtextfx/src/main/java/org/fxmisc/richtext/model/EditActions.java

When doing drag-and-drop then the moved text was not selected (as in other text editors).

select moved text after drag-and-drop

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Add API to get paragraph bounds if visible

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Feature: map visible paragraph index to all paragraph index & vice versa

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Addresses an issue raised in #606

Expose viewport dirty as public API

---

CONTRIBUTING.md

Resolves most of the things in #615

Clarify contributing guidelines

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink/TextHyperlinkArea.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java

The moved code is IMHO an implementation detail that belongs to class `ParagraphText` and not to demos.
As stated in [this comment](https://github.com/FXMisc/RichTextFX/pull/614#issuecomment-336666986) I'm still not sure whether binding `TextExt.selectionFill` to `TextExt.fill` makes any sense. I can't see any difference without this binding. In PR #428 I've also removed this binding and replace with binding `TextExt.selectionFill` to `ParagraphText.highlightTextFill`, but as long as the JDK is not fixed, styling text color of selection does not work at all...

moved ParagraphText specific code from createStyledTextNode() methods to class ParagraphText

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyleActions.java
richtextfx/src/main/java/org/fxmisc/richtext/TextEditingArea.java
richtextfx/src/main/java/org/fxmisc/richtext/ViewActions.java

Adds API to get the viewport's height and show a specific region of a given paragraph
Otherwise, cleans up the source code a bit more by
- removing unused methods
- using properties and default methods to reduce boilerplate
- put package-private and private methods in their own spots in the source code.

Get viewport height; show paragraph region; clean up source code (boilerplate & organization)

---

README.md

JabRef is a bibliography management suite currently migrating to JavaFX. Our last published version uses RichTextFX.

Add JabRef to the projects using RichTextFX

---

.travis.yml

Increase Mac build's TestFX setup timeout to 5 seconds

---

richtextfx/src/main/java/org/fxmisc/richtext/model/GenericEditableStyledDocument.java
richtextfx/src/main/java/org/fxmisc/richtext/model/GenericEditableStyledDocumentBase.java
richtextfx/src/main/java/org/fxmisc/richtext/model/ReadOnlyStyledDocument.java
richtextfx/src/main/java/org/fxmisc/richtext/model/ReadOnlyStyledDocumentBuilder.java
richtextfx/src/main/java/org/fxmisc/richtext/model/SimpleEditableStyledDocument.java
richtextfx/src/test/java/org/fxmisc/richtext/model/ReadOnlyStyledDocumentBuilderTest.java

Resolves #646 
No longer adddresses #644
Before this, the initial document must always be empty

Allow initializing an [Editabled/ReadOnly]StyledDocument with content

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Fix for #650 (Read only pseudo class is misspelled in GenericStyledArea)

Corrected misspelled read-only pseudo class

---

richtextfx/build.gradle
richtextfx/src/main/java/org/fxmisc/richtext/util/UndoManagerInactivityWrapper.java
richtextfx/src/main/java/org/fxmisc/richtext/util/UndoUtils.java

WellBehavedFX now includes more documentation
UndoFX now includes the UndoManagerInactivityWrapper class' implementation in a more efficient manner

Update dependencies: WellBehavedFX and UndoFX

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/FxmlTest.java
richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/FxmlTester.java
richtextfx/src/integrationTest/java/org/fxmisc/richtext/mouse/ClickAndDragTests.java
richtextfx/src/integrationTest/resources/org/fxmisc/richtext/api/FxmlTest.fxml
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java
richtextfx/src/main/java/org/fxmisc/richtext/ViewActions.java

RFE implementation for #655
The methods in `ViewActions` related to the following have been @**Deprecated**:
> onOutsideSelectionMousePress
> onInsideSelectionMousePress
> onNewSelectionDragEnd
> onSelectionDrop
They have been replaced with FXML friendly equivalent (non default) interface methods:
> onOutsideSelectionMousePress**ed**
> onInsideSelectionMousePress**ed**
> onNewSelectionDrag**Finished**
> onSelectionDropp**ed**
Which have been implemented in `GenericStyledArea`. The references to the deprecated methods in `GenericStyledAreaBehavior` have been changed to the new ones.
During this process it was found that the `onNewSelectionDragEnd/Finished` functionality hadn't been implemented in `GenericStyledAreaBehavior`  and this was rectified as well.

RFE implementation for #653 / #655

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/InlineCssTextArea.java

Resolves #676.
In addition to fixing that issue, I also bumped the type of the area's segmentOps field from `SegmentOps` to `TextOps`. The area's constructor already requires the latter type, so this just makes it easier to call `StyledDocument`-related methods.
It is unlikely for this bug to be reproduced in the other areas because their SEG generic isn't purely text. Still, I wonder whether the method names should be changed to prevent problems like this from arising in the future. I think one test that could be written for this would be to check the number of visible paragraphs after constructing each kind of area.

Use correct replace method when SEG is String

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/mouse/ClickAndDragTests.java
richtextfx/src/main/java/org/fxmisc/richtext/ViewActions.java

Addresses some of the issues raised in #656.
Resolves #679 and #680.

Skip failing Mac test; correct Javadoc for some mouse hooks

---

richtextfx/src/main/java/org/fxmisc/richtext/model/Paragraph.java
richtextfx/src/test/java/org/fxmisc/richtext/model/ParagraphTest.java

This is a fix for an issue discovered in #449 where styles were not being applied to empty paragraphs. In that issue it was causing an IndexOutOfBoundsException within JavaFX.

Updated Paragraph to apply styles to empty paragraphs.

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/RichText.java

Fixes #452.
The issue can still happen, but this at least forewarns such people about it better.

Only save/load ".rtfx" files; warn about file format changes

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/ReplaceTextTests.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
richtextfx/src/main/java/org/fxmisc/richtext/SelectionImpl.java

This is a fix for #689  ArrayIndexOutOfBoundsException in `ParagraphText.getRangeShapeSafely` after calling `replaceText` under certain conditions.

Fix replaceText IOOBE

---

richtextfx/src/main/java/org/fxmisc/richtext/model/Paragraph.java
richtextfx/src/test/java/org/fxmisc/richtext/model/ParagraphTest.java

Fix for #696

---

richtextfx/build.gradle
richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/MultiChangeTest.java
richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/UndoManagerTests.java
richtextfx/src/main/java/org/fxmisc/richtext/CaretNode.java
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/MultiChangeBuilder.java
richtextfx/src/main/java/org/fxmisc/richtext/SelectionImpl.java
richtextfx/src/main/java/org/fxmisc/richtext/TextEditingArea.java
richtextfx/src/main/java/org/fxmisc/richtext/model/EditableStyledDocument.java
richtextfx/src/main/java/org/fxmisc/richtext/model/GenericEditableStyledDocumentBase.java
richtextfx/src/main/java/org/fxmisc/richtext/model/ReadOnlyStyledDocument.java
richtextfx/src/main/java/org/fxmisc/richtext/model/Replacement.java
richtextfx/src/main/java/org/fxmisc/richtext/util/UndoManagerInactivityWrapper.java
richtextfx/src/main/java/org/fxmisc/richtext/util/UndoUtils.java

Resolves #574.
One feature still lacking in this PR: the UndoManager cannot undo/redo a list of changes because I still need to think through how two lists of changes should be merged and what their identity values would be.

Allow multiple portions of an area's document to be updated in one call

---

README.md

Update README.md to include PsychSQL (a one-file SQL client on top of JDBC) in the "Who uses RichTextFX?" section.

Add PsychSQL to list of projects that use RichTextFX

---

richtextfx/src/main/java/org/fxmisc/richtext/model/Paragraph.java
richtextfx/src/test/java/org/fxmisc/richtext/model/SimpleEditableStyledDocumentTest.java

Fix `getStyleRangeAtPosition()` bug

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywords.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywordsAsync.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/SpellChecking.java
richtextfx/src/main/java/org/fxmisc/richtext/model/EditableStyledDocument.java
richtextfx/src/main/java/org/fxmisc/richtext/model/RichTextChange.java

Fixes #720 
Also cleans up the demos to use the new `multiPlainChanges()` API introduced in #695

Prevent `multiPlainChanges()` from emitting an empty list

---

README.md
richtextfx-demos/README.md

Here's a quick fix to #733. I also removed the word "below" and add the missing "Demo" related to the links

Fixed the links pointing to the demo source pages

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/mouse/ClickAndDragTests.java
richtextfx/src/main/java/org/fxmisc/richtext/CaretNode.java
richtextfx/src/main/java/org/fxmisc/richtext/CaretSelectionBind.java
richtextfx/src/main/java/org/fxmisc/richtext/CaretSelectionBindImpl.java

Fix bug: wrongly calculated value used for `moveToParEnd`

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/TextBuildingUtils.java
richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/ParagraphIndexMappingTests.java
richtextfx/src/integrationTest/java/org/fxmisc/richtext/keyboard/PageUpDownTests.java
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Fix all par index bug

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/caret/BoundsTests.java
richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/caret/PositionTests.java
richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/selection/PositionTests.java
richtextfx/src/main/java/org/fxmisc/richtext/CaretNode.java
richtextfx/src/main/java/org/fxmisc/richtext/SelectionImpl.java

Fix bug: Caret/Selection positions should be updated correctly when change occurs at their position

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

Resolves #627 
Fix memory leak of ParagraphText through listeners:
- Make listeners static class
- Use WeakReference to refer to the ParagraphText from the listeners
- Remove the listeners if the ParagraphText is garbage collected.

Issue #627 Extreme memory usage with large blocks of text

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

This PR immediately removes listeners (in class `ParagraphText`) from `SelectionPath` and `Caret` on disposal instead of waiting for GC (this improves PR #779, issue #627). Without this change, disposed ParagraphText objects may still listen to selection and caret and do some useless stuff.
Since the weak listeners added in PR #779 are no longer necessary, I've removed the listener classes again and moved selection and caret listeners code back to constructor (saves 100 lines of code).

ParagraphText: immediately remove listeners from selections and carets on disposal

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

If a line contains a custom object (e.g. image in RichText demo) and you apply background color to text after that image, then the background is painted one character to the left where it should be painted.
The problem is simply that the image is not considered when calculating the start position of the background color.
This PR fixes issue #638

fix position of background, border and underline shapes in case that the line contains custom objects 

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java

Typing Ctrl+A or Cmd+Z on alternate keyboard layouts like Dvorak or German doesn't get recognized properly. (See issue #799)

Fixes #799 Alternate keyboard layouts not supported

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/VisibleParagraphTest.java
richtextfx/src/main/java/org/fxmisc/richtext/model/GenericEditableStyledDocumentBase.java

fixes #777 and fixes #788 
details are here https://github.com/FXMisc/RichTextFX/issues/777#issuecomment-449523388

Paragraph list trim fix

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
richtextfx/build.gradle
richtextfx/src/integrationTest/java/org/fxmisc/richtext/MultiReleaseJarTest.java
richtextfx/src/main/java/org/fxmisc/richtext/JavaFXCompatibility.java
richtextfx/src/main/java/org/fxmisc/richtext/TextFlowExt.java
richtextfx/src/main/java9/org/fxmisc/richtext/JavaFXCompatibility.java
richtextfx/src/main/java9/org/fxmisc/richtext/TextFlowExt.java
richtextfx/src/main/java9/org/fxmisc/richtext/TextFlowLayout.java
richtextfx/src/main/java9/org/fxmisc/richtext/TextFlowSpan.java

Added alternative TextFlowExt that doesn't use private JDK method TextFlow.getTextLayout()
This is not Java 8 compatible and as a first step is being included as a multi-release jar which will eliminate the need for `--add-exports` and `--add-opens`
This addresses issues #270 and #647

Mrjar config and source

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java

The insets were removed from the "overhead" when they should have been
added. This was asking the text for its preferred height if it had
(width + insets) space, rather than (width - insets).
Because of this, some paragraphs give a preferred height of one line
less than they should (because they wouldn't need to wrap given the
extra space that's actually occupied by the insets).
Fixes #809

Fix height paragraph box height calculation

---

richtextfx/src/main/java/org/fxmisc/richtext/model/Paragraph.java
richtextfx/src/test/java/org/fxmisc/richtext/model/ParagraphTest.java

With reference to issue #815 Paragraph returns an incorrectly styled sub-sequence when the paragraph contains multiple styles and a sub-sequence is requested from the end of the paragraph which is inside a style.

Fix Paragraph returning incorrectly styled subsequence

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

In ParagraphText.dispose() listeners need to be remove from selections and carets before clearing, otherwise the clear triggers a selection path update that results in an errant selection path appearing at the current cursor position.

Fix for #812 caretBounds graphic bug

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/HitTests.java
richtextfx/src/integrationTest/java/org/fxmisc/richtext/keyboard/PageUpDownTests.java
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Changed page up and down behaviour as described in issue #688

RFE #688 Changed page up and down behaviour

---

richtextfx/src/main/java9/org/fxmisc/richtext/TextFlowExt.java

Fixes #833 where the caret isn't positioned correctly at the end of the last line in a multiline paragraph.

Fixed caret position off by one on wrapped multiline

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/SelectionPath.java
richtextfx/src/main/resources/org/fxmisc/richtext/styled-text-area.css

The highlight fill property has been broken since 0.9.0 as a result of the multiple selection capability being added.
It can now be set again via CSS with either of:
```css
.styled-text-area .selection { -fx-fill: lime; }
/* or */
.styled-text-area .selection { -fx-highlight-fill: lime; }
/* or */
.styled-text-area .main-selection { -fx-highlight-fill: pink; }
/* or */
.styled-text-area .main-selection { -fx-fill: pink; }
```

Fix highlight fill

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/Selection.java
richtextfx/src/main/java/org/fxmisc/richtext/SelectionImpl.java

This PR is for RFE  #841 adding the following API to GenericStyledArea:
```java
setLineHighlighterFill( Paint highlight )
setLineHighlighterOn( boolean show )
isLineHighlighterOn()
```
The highlighter can be styled via CSS using selectors from Path, Shape, and Node. For example:
```css
.styled-text-area .line-highlighter { -fx-fill: lime; }
/* or */
.line-highlighter { -fx-highlight-fill: lime; }
```
Any added custom Selections can now also be styled via CSS using the selection's name.

Added line highlighter enhancement

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywordsDemo.java
richtextfx/src/main/java/org/fxmisc/richtext/CodeArea.java

1. Addressed CodeArea #837 Double-clicking a word containing numbers with underscore does not select the whole word.
2. Added auto-indent API when Enter is pressed to JavaKeywordsDemo.

Enhancements to CodeArea and JavaKeywordsDemo

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Fix for when selecting text downwards over multiple lines with line-highlighting on then the selection on the last line is hidden by the line highlight. Refers to #845

Fix highlight masking selection of text

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Fixed [#845](https://github.com/FXMisc/RichTextFX/pull/845#issuecomment-552252829) where when typing on an empty line the highlighter wasn't rendering from the beginning of the line.

Fixed not highlighting from beginning of line after adding text when

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java

Fixes [#862](https://github.com/FXMisc/RichTextFX/issues/862#issuecomment-551412428) where line spacing is not being honored between paragraphs.

Apply line spacing property between paragraphs as well

---

richtextfx/src/main/resources/org/fxmisc/richtext/styled-text-area.css

Fixes [#738](https://github.com/FXMisc/RichTextFX/issues/738#issuecomment-555592054) where a thin white line appears between paragraphs but only if navigating with scrollbar/mouse.

Changed styled-text-area CSS

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/selection/PositionTests.java
richtextfx/src/main/java/org/fxmisc/richtext/CaretSelectionBindImpl.java

Fixes #874 anchor properties not updating correctly if they have listeners attached.
The problem seems to come down to the `internalStartedByAnchor` Boolean property not firing on each invocation of `setValue`, but only when the actual value held changes.
The most non intrusive and safest fix, I feel, is to just toggle the Boolean property when needed in order to fire any relevant change listeners.

Added test and anchor properties fix

---

richtextfx/src/main/java/org/fxmisc/richtext/util/UndoUtils.java

Added convenience method to UndoUtils to create a NO OP undo manager.

Add no op undo manager

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

Fixed initial HashMap and HashSet capacity values.
With a load factor of .75 the lowest initial capacity should be 2 and not 1 otherwise the collection will resize immediately upon the first addition.

Fixed initial collection capacity values.

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

Reverts FXMisc/RichTextFX#884
Upon reviewing the Java source code I see that I was mistaken.

Revert "Fixed initial collection capacity values."

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

Fixed memory leak in ParagraphText (redone)

---

richtextfx/src/main/java/org/fxmisc/richtext/InlineCssTextField.java
richtextfx/src/main/java/org/fxmisc/richtext/StyleClassedTextField.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextField.java
richtextfx/src/main/resources/org/fxmisc/richtext/styled-text-field-caspian.css
richtextfx/src/main/resources/org/fxmisc/richtext/styled-text-field-modena.css

Addresses RFE #764, #635 and #64 by adding the following styled text fields, namely `InlineCssTextField`,  `StyleClassedTextField`, and a their parent `StyledTextField<PS, S>`.

Added styled text fields

---

richtextfx/src/main/java/org/fxmisc/richtext/StyledTextField.java
richtextfx/src/main/java/org/fxmisc/richtext/package-info.java

Prevent wrap text from being set true for text fields.

Prevent wrap text from being set true for text fields.

---

richtextfx/src/main/java/org/fxmisc/richtext/InlineCssTextField.java
richtextfx/src/main/java/org/fxmisc/richtext/StyleClassedTextField.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextField.java
richtextfx/src/main/resources/org/fxmisc/richtext/styled-text-field-caspian.css
richtextfx/src/main/resources/org/fxmisc/richtext/styled-text-field-modena.css

JavaFX's `TextField` has a property and associated methods to determine the alignment of text in the field.
This PR adds similar methods to _StyledTextField_ as a convenience and to aid switching from `TextField`.
The only difference is that `TextField` used `Pos` as its value while _StyledTextField_ uses `TextAlignment`.
Note that `TextAlignment.JUSTIFY` isn't currently accommodated.
`-fx-alignment`  can be used for CSS styling.

Added convenient text field alignment capabilities

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/StyledTextField.java

Resolves #256 Add support for a prompt / placeholder text when area is empty.
This adds `setPlaceholder( Node )` support to _GenericStyledArea_ and `setPromptText( Text )` support to _StyledTextField_.

Add placeholder enhancement

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

In the first implementation the place holder was always in the scene graph and its visibility toggled.
This implementation adds and removes the place holder from the scene graph instead.

Improved placeholder implementation

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/UndoManagerTests.java
richtextfx/src/main/java/org/fxmisc/richtext/model/ReadOnlyStyledDocument.java

Fixes #904 
The problem turned out to be that when ReadOnlyStyledDocument does a replace then it is assumed that the provided replacement is the actual change that has occurred in the document. This is not always the case though due to paragraph concatenation having various rules determining if the left or right hand side style is going to be used if either of the paragraphs is empty.

Fixed RichTextChange reported by ReadOnlyStyledDocument replace

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/UndoManagerTests.java
richtextfx/src/main/java/org/fxmisc/richtext/model/RichTextChange.java
richtextfx/src/main/java/org/fxmisc/richtext/util/UndoUtils.java

Relates to #903 Unexpected change in UndoManager
When a text style is changed while the undo manager is suspended then it is expected that undo or redo can occur afterwards without the undo manger complaining about any style differences it may encounter.

Provide suspendable undo manager

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/UndoManagerTests.java
richtextfx/src/main/java/org/fxmisc/richtext/util/UndoUtils.java

Fixes #912 After undo/redo, new text is inserted at the end.
My initial attempt to fix this involved changing `CaretNode` and `SelectionImpl`, but doing so broke the org.fxmisc.richtext.api.caret `PositionTests`. So instead `UndoUtils` got hijacked to accomplish the desired behavior.

Fix post undo/redo caret position

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/ParagraphIndexMappingTests.java
richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/ReplaceTextTests.java
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/model/GenericEditableStyledDocumentBase.java

Fixes #913 which was introduced through PR #795 
This PR reverts the 795 change and implements a more robust and direct method for determining the visible paragraph index or the 'global' paragraph index, instead of using comparison loops. (Resolves #777)
795 also addressed #788 for which this PR adds a test and simply catches the exception for this corner case.

Fix scrollbar jump

---

richtextfx/src/main/java/org/fxmisc/richtext/Caret.java
richtextfx/src/main/java/org/fxmisc/richtext/CaretSelectionBindImpl.java
richtextfx/src/main/java/org/fxmisc/richtext/CodeArea.java
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/NavigationActions.java
richtextfx/src/main/java/org/fxmisc/richtext/SelectionImpl.java
richtextfx/src/main/java/org/fxmisc/richtext/TextEditingArea.java

Closes #851
If locale settings are needed on a per paragraph or sentence basis then make sure that there's some way of storing and retrieving the sentence or paragraph's locale from the text or paragraph's **style**. Then override `getLocale` to access the locale from the style and return it.

Added getLocale and setLocale for BreakIterator use.

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Fixes #932 
Ordinarily when a caret ends a selection in the target paragraph and scrolling left is required to follow 
the caret then the selection won't be visible as it'll be just off to the left of the screen.
This PR adds a check for this scenario and adjusts follow caret so that the selection becomes visible as well.

Accommodate selection when following caret

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Addresses RichTextFX issues #77, #171, #674, and #930 as well as Flowless issue [#30](https://github.com/FXMisc/Flowless/issues/30) and associated pull request [#77](https://github.com/FXMisc/Flowless/pull/77)
Thanks to **@aimosg** for code snippet [here](https://github.com/FXMisc/RichTextFX/issues/674#issuecomment-429606510).

RFE: Auto height

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Addresses this [comment](https://github.com/FXMisc/RichTextFX/issues/937#issuecomment-674319602) of #937 fixing the last line not being displayed fully by follow caret.
Note that this doesn't fix the NoSuchElementException if highlight is on as reported in the issue.

Follow caret show complete line fix

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Addresses a side issue reported at the bottom of this [comment](https://github.com/FXMisc/RichTextFX/issues/937#issuecomment-675846754) where the full line wasn't being highlighted when text wrap is off.
Note that this doesn't fix the primary issue mentioned in the linked comment, nor the NoSuchElementException if highlight is on.

Fix nonwrap line highlighter width

---

richtextfx/src/main/java/org/fxmisc/richtext/model/ReadOnlyStyledDocument.java

Fixes issue raised in this [comment](https://github.com/FXMisc/RichTextFX/issues/937#issuecomment-675846754) where line highlighting misbehaves when using `insert` instead of `insertText` to add a multiple paragraph text block in one go. This happened  because the text block wasn't being parsed into paragraphs but was just being added as a single giant "paragraph".

Fix multi paragraph insert creation

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywordsDemo.java

Addresses #926 Syntax highlighting is extremely slow.

Improved syntax highlighting demo

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/brackethighlighter/BracketHighlighter.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/brackethighlighter/BracketHighlighterDemo.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/brackethighlighter/CustomCodeArea.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/brackethighlighter/TextInsertionListener.java
richtextfx-demos/src/main/resources/org/fxmisc/richtext/demo/brackethighlighter/bracket-highlighter.css

Added demo for bracket highlighting for [] () {} <> type of brackets in CodeArea. Closes #958

Added bracket highlighter demo

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/brackethighlighter/CustomCodeArea.java

This PR fixes the issue that brackets do not clear on rich text changes in bracket highlighter demo.
Steps to reproduce:
1. Enter the following character sequence `[]` at position 0 (empty code area).
2. Select the entered character sequence `[]` and copy it with keyboard shortcut (copy rich text).
3. Place caret at position 1 in between the two brackets (position 0 and 1 gets highlighted).
4. Paste the copied rich text using keyboard shortcut at position 1 (position 1, 2, and 3 are highlighted).
**Actual result:**
Position 1, 2, and 3 are highlighted
**Expected result:**
Position 1 and 2 are highlighted
**Resolution:**
Overriding `replace(int, int, StyledDocument<PS, SEG, S>)` instead of `replaceText(int, int, String)` fixes this issue.
This is because `replaceText(int, int, String)` is …

Fixed issue with replaceText() not called on rich text changes in BracketHighlighterDemo

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

The width listener was causing an NPE, but is also no longer needed due to a previous PR #948 that fits the line highlight shape to the parent's width. This essentially reverts PR #857 without regression.

Removed linehighlighter width listener

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java

Fixes #967 OSX: Entering curly braces and brackets is broken.
This is likely due to a regression by PR #922. This fix realigns the code to look/behave more like the way it did before.

Realign controlKeysFilter with previous behavior

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywordsDemo.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/BulletFactory.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/ParStyle.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/RichTextDemo.java
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/InlineCssTextArea.java
richtextfx/src/main/java/org/fxmisc/richtext/LineNumberFactory.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java
richtextfx/src/main/java/org/fxmisc/richtext/StyleClassedTextArea.java
richtextfx/src/main/resources/org/fxmisc/richtext/styled-text-area.css

This PR implements Paragraph Folding, resolves #107 and closes #955
Folded/collapsed paragraphs can be copied, pasted, and saved. A section of text containing a fold can also be folded without losing the contained fold, and each layer only unfolds itself. Any folded/collapsed text is still part of the document and can be manipulated as usual. The LineNumberFactory has also been modified to show a clickable "+" symbol on the line before a fold.
For historical purposes or for whoever cares to scrutinize how this was implemented and to defend any WTF thoughts, some explanatory notes are needed. Rest assured that careful consideration has been given and although not necessarily the best way of accomplishing folding it wasn't just arbitrarily or haphazardly slapped on even though it may appear …

Paragraph Folding

---

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywordsDemo.java

Fixes #970 
The JavaKeywordsDemo was recently updated with a way to only compute highlighting on the visible paragraphs instead of on the whole contents of the editor. However the regular expression pattern for comments was originally designed to work on a block of text and not lines of text, which is why the multi-line comments aren't being correctly styled (when using the visible paragraphs highlighting method).
This PR updates the COMMENT_PATTERN to address this, although it's not perfect.

Fix JavaKeywordsDemo comment pattern

---

README.md

Hi there,
I used RichTextFX in my project [BasicCAT](https://github.com/xulihang/BasicCAT), which is a computer-aided translaton tool to style tags, whitespaces and furthurmore. I would like to know if it could be included in the section 'Who uses RichTextFX?'.
Regards

Add BasicCAT to README

---

richtextfx/src/integrationTest/java/org/fxmisc/richtext/keyboard/PageUpDownTests.java
richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Modified Page up to go to first line when visible, and Page down to go to last when visible.

Page up and down tweak

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

Fixes Ctrl+A misbehavior when the last paragraph is folded, as reported in PR comment [here](https://github.com/FXMisc/RichTextFX/pull/965#issuecomment-706268116).

Fix Ctrl+A and Ctrl+End fold navigation

---

richtextfx/src/main/java/org/fxmisc/richtext/LineNumberFactory.java
richtextfx/src/main/resources/org/fxmisc/richtext/styled-text-area.css

Fixes #988 Fold indicator styling via CSS not working

Fix custom fold CSS not being applied

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Fixes #998 where the incorrect first visible paragraph gets returned when navigating backwards through the list.

Updated visibleParToAllParIndex

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
richtextfx/src/main/resources/org/fxmisc/richtext/styled-text-area.css

I've experienced CSS errors in production with regards to the new paragraph folding code, even though I don't use folding.
> WARNING: Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in module javafx.graphics@11.0.6 of loader 'platform')' while converting value for '-fx-background-color' from rule '*.text-area' in stylesheet jrt:/javafx.controls/com/sun/javafx/scene/control/skin/caspian/caspian.bss
Oct 26, 2020 1:40:49 PM javafx.scene.CssStyleHelper calculateValue
I've narrowed down these errors to being triggered by the `skipOverFoldedParagraphs` method, which makes sense because before this PR it was being called whenever the paragraph …

Added foldCheck skipping

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

It turns out that my fix for #939 causes the caret to not be properly followed in certain cases #1017.
The fix for the latter issue was to revert back to the way the caret bounds was being acquired previously and so undoing the fix for the former problem. This PR basically combines the previous two fixes into one. 
I confess that this is now probably more of a hack, but it does address the problem raised in 939 without breaking anything.
The actual problem seems to be that the new paragraph hasn't received the/a caret at this point. Since this is a corner case and I believe happens infrequently I don't feel it justifies spending a lot of time to find a more elegant/proper solution. Hence this PR ;-)

Follow caret regression fix

---

richtextfx/src/main/java/org/fxmisc/richtext/CaretNode.java

When you install a mouse handler on a TextExt area using setOnMouseClicked() or similar, there's a small chance that your mouse click will be ignored. This happens approximately one time in ten in my experience.  The problem occurs when you click at the exact same position as the flashing caret while the caret is visible; this confuses the java FX mouse-picking algorithm, which causes the event to be sent to the ParagraphText node rather than the TextExt. The fix is simply to make the caret transparent to mouse picking.
See this link for more evidence + screenshots : https://github.com/FXMisc/RichTextFX/issues/124
(should be a safe change, I can't think of any reason you'd want the caret to be pickable)

Make CaretNode transparent to mouse picking (fixes #124)

---

richtextfx/src/main/java/org/fxmisc/richtext/StyledTextField.java

For some reason the initial height calculation hack broke, so this fixes it.

StyledTextField initial height fix

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java

Added overwrite mode

---

README.md

Update the README file:
* Correct minor formatting typos
* Use active voice (shorter sentences)
* Alphabetize list of applications using RichTextFX
* Add KeenWrite to applications list
* Add missing backtick
* Fix parens in code example

Fix typographical errors, simpler sentences, add KeenWrite

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Fixes #1058 requestFollowCaret() does not show selection outside area on the right.
Note that this refers to / possibly impacts original #932.

Followcaret with selection update

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Resolves #1073 textArea.getCharacterBoundsOnScreen(i, i) gives inappropriate bounds
Added code to return cursor like bounds when from == to.

fix getCharacterBoundsOnScreen

---

richtextfx/src/main/java9/org/fxmisc/richtext/TextFlowLayout.java

Fixes #1071 wrapped lines get skipped when navigating with up/down arrow keys.
This was because the previous implementation wasn't DPI robust. See [#1071 comment](https://github.com/FXMisc/RichTextFX/issues/1071#issuecomment-1018391842)

Changed staggered text detection

---

richtextfx/src/main/java/org/fxmisc/richtext/StyledTextField.java

Fixes [comment](https://github.com/FXMisc/RichTextFX/issues/177#issuecomment-1135232636) on #177
Seems like SceneBuilder analyses jar files on a background thread and not on the FX thread, so RichTextFX text fields aren't imported as custom components.

Fix for SceneBuilder compatibility

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Addresses #1118 
If `append` or `replace` methods are invoked with a **null style** then behave like `replaceText`

Added null style check

---

README.md

Hey all, I use RichTextFX in a project I recently released and would like to list it on the README. It's been a pleasure to work with it so far :)

Add JVM explorer to README project list

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
richtextfx/src/main/java/org/fxmisc/richtext/TextExt.java
richtextfx/src/main/java/org/fxmisc/richtext/TextFlowExt.java
richtextfx/src/main/java9/org/fxmisc/richtext/TextFlowExt.java

Basic implementation of wavy underlines as described in #1131.
Adds two properties -- "wave" to control the radius of arc used to draw wavy lines, and "offset" to adjust the distance between text and underline, since it can be necessary to increase this for legibility when a wavy underline is in use.  Probably better names are possible.
These are used in `TextFlowExt#getUnderlineShape` to modify the shape produced.  If no radius is specified then a line is drawn as previously; otherwise a series of arcs is drawn, which replicates the appearance of the wavy underlines in common programs such as Microsoft Word.
I have only implemented the wavy-line shape in the Java 9+ version of the class because I can see there's an open question whether it's even worth supporting Java 8 any more (and my …

Support wavy underlines (issue #1131)

---

richtextfx/src/main/java9/org/fxmisc/richtext/TextFlowLayout.java

Fixes #1134 getParagraphLinesCount() get wrong line count
This was because all lines in a multi-line text node was being incorrectly added to the paragraph count.
Rearranged the line count logic to fix.

Fixed multi line text calculation

---

richtextfx/src/main/java/org/fxmisc/richtext/LineSelection.java

LineSelection sometimes results in a index out of bounds exception when pressing Ctrl+Home to jump to the very top of a document.

Fixed LineSelection index out of bounds exception

---

README.md

Been using RichTextFX for a little over 4 years now, [been quite happy with it](https://github.com/Col-E/Recaf).

Add Recaf to 'Who uses RichTextFX'

---

richtextfx-demos/README.md
richtextfx-demos/build.gradle
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/DemoLauncher.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/MultiCaretAndSelectionDemo.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/ShowLineDemo.java
richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/SpellCheckingDemo.java

Thanks @afester for DemoLauncher and updating build.gradle

Add DemoLauncher from afester

---

README.md

Both my [JFXDevTools](https://github.com/Zev-G/JFXDevTools) and [JfxIDE](https://github.com/Zev-G/JfxIDE) have been using RichTextFX and the experience has been super!
JFXIde:
JFXPlus:

Add to "Who uses RichTextFX?"

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java

Fixes #1168 wrapTextProperty() is temporarily ignored when inserting characters on a long line

Set TextFlow prefWidth to max for no wrapping

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java

Fixes #1192, where if an area is NOT the first Node in a layout (e.g. its the second item in a HBox) then the placeholder position was being incorrectly calculated.

Fixed placeholder position in some layouts

---

richtextfx/src/main/java/org/fxmisc/richtext/model/StyleSpan.java
richtextfx/src/main/java/org/fxmisc/richtext/model/StyleSpans.java
richtextfx/src/main/java/org/fxmisc/richtext/model/StyleSpansBuilder.java
richtextfx/src/test/java/org/fxmisc/richtext/model/ParagraphTest.java

Resolves #1231 How to get real size of one span at position X
With this PR a developer can now get the range of a style that crosses paragraphs.
Both the requested position and the returned _IndexRange_ are relative to the start of the requested _StyleSpans_.
Usage Example:
```java
var ss = codeArea.getStyleSpans( 0, codeArea.getLength() );  // From beginning to end
var range = ss.getStyleRange( position );  // So range is from beginning
```

Added getStyleRange to StyleSpans

---

README.md

The [PMD designer](https://github.com/pmd/pmd-designer/) is part of the [PMD](https://github.com/pmd/pmd) project, which has more than 4K stars. It uses RichTextFX since a rewrite from scratch in 2017. We built some advanced features on top of RichTextFX, like layered highlighting and AST selection modes. We also use a lot the ReactFX library and programming model. I'm very grateful for these projects :)

Add PMD designer to README

---

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java

Fixes #1253 Keybindings (like Control + C) doesn't work on alternative keyboard layouts (since JavaFX 21)

Fix Keybindings not working on alternative keyboard layouts

---

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java

Fixes #1257  area.getStylesheets().clear() adds 1px to underline width.

Fixed double underline when gap is zero

---

richtextfx/src/main/java/org/fxmisc/richtext/TextFlowExt.java

Resolves #1282 TextFlowExt incompatible with JavaFX 25

TextFlowExt removed clashing getUnderlineShape method
