richtextfx/src/main/java/org/fxmisc/richtext/model/NavigationActions.java
Public API documentation was missed.
=> Line to Paragraph

richtextfx/src/main/java/org/fxmisc/richtext/model/Paragraph.java
From #345, this assert statement should have been turned into an exception when paragraph become public
=> Turn assert statement into IllegalArgumentException

richtextfx/src/main/java/org/fxmisc/richtext/model/EditActions.java, richtextfx/src/main/java/org/fxmisc/richtext/model/TextChange.java
=> Fix move selected text bug

richtextfx/src/main/java/org/fxmisc/richtext/model/PlainTextChange.java, richtextfx/src/main/java/org/fxmisc/richtext/model/RichTextChange.java, richtextfx/src/main/java/org/fxmisc/richtext/model/TextChange.java, richtextfx/src/test/java/org/fxmisc/richtext/model/SimpleEditableStyledDocumentTest.java
=> Fix regression: changing empty paragraph's style is a valid change

README.md
Added Juliar to the RichTextFX project since we are using it.
https://github.com/juliarLang/juliarFuture
=> Added Juliar Programming Language (JuliarFuture) Project

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/RichText.java, richtextfx/build.gradle, richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java, richtextfx/src/main/java/org/fxmisc/richtext/model/GenericEditableStyledDocumentBase.java, richtextfx/src/main/java/org/fxmisc/richtext/model/TextChange.java, richtextfx/src/main/java/org/fxmisc/richtext/model/UndoActions.java
I took a short break from homework.
=> Update undo fx

richtextfx/src/main/java/org/fxmisc/richtext/CssProperties.java, richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java, richtextfx/src/main/java/org/fxmisc/richtext/TextExt.java
This addresses #485.
However, the build currently fails due to an NPE somewhere. The first commit works; the second doesn't. I'm not sure why.
=> Optimize css meta data list

richtextfx/src/main/java/org/fxmisc/richtext/CustomCssMetaData.java
=> Fix regression due to typo

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java, richtextfx/src/main/java/org/fxmisc/richtext/TextExt.java
Resolves #346.
Technically, a few additional stroke-related things could be added (cap, line offset, etc.), but for now I'll wait until someone requests them. It won't be difficult to add them anyways.
=> Support adding border strokes around a section of text

richtextfx/build.gradle
=> Add support for OSGI

richtextfx/src/integrationTest/java/org/fxmisc/richtext/keyboard/CutCopyPasteTests.java, richtextfx/src/main/java/org/fxmisc/richtext/model/Paragraph.java
=> Fix regression: use only valid indexes for setting a merged segment

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/CaretTests.java
=> Fix Mac build error

richtextfx/src/main/java/org/fxmisc/richtext/model/ReadOnlyStyledDocument.java
=> Make more of ROSD's replace API public, not package-private

gradle/wrapper/gradle-wrapper.properties, richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/RichText.java
Upgrade Gradle to support Java 9.
And some small changes in RichText.java to test a pull request.
=> Upgrade Gradle to 4.4.1-bin (Binary-only) and change hash code. And small changes in RichTextFx.java.

richtextfx/src/main/java/org/fxmisc/richtext/EditActions.java
Fully implements idea in #574 with support implemented in #695
=> Move selected text should be one change

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/MultiChangeTest.java, richtextfx/src/main/java/org/fxmisc/richtext/util/UndoUtils.java
Fixes #701.
Thanks again @JFormDesigner for the test case! It made tracking down this regression and testing against it much easier.
=> Use absolute replacements for undo and redo

richtextfx/src/integrationTest/java/org/fxmisc/richtext/SceneGraphTests.java, richtextfx/src/integrationTest/java/org/fxmisc/richtext/style/StylingTests.java, richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
=> Use correct class in `instanceOf` check; provide faster equals method

richtextfx/src/integrationTest/java/org/fxmisc/richtext/SceneGraphTests.java, richtextfx/src/integrationTest/java/org/fxmisc/richtext/style/StylingTests.java, richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
=> Fix unconsecutive style issue

richtextfx/build.gradle
Updates dependency:
- Push/Pop-able InputMaps are now available (helpful for auto-complete)
=> Update WellBehavedFX to 0.3.3

README.md
Adds Greenfoot as a project that uses RichTextFX
=> Updates README.md to add Greenfoot as a project that uses RichTextFX

README.md
=> Added Everest to 'Who uses RichTextFX?'

README.md
XR3Player uses RichTextFX , pull request :) #756
=> XR3Player uses RichTextFX

README.md
George has been using RichTextFX since 2015.
It also uses Flowless directly in a custom-build Clojure editor.
=> Add to Who uses

README.md
=> Add who uses

README.md
=> Add Astro IDE Project

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java, richtextfx/src/main/java/org/fxmisc/richtext/ViewActions.java
Removed deprecated methods from ViewActions interface and the GenericStyledArea implementation.
=> Remove deprecated methods

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
Fixed mistakenly using a lambda as the parameter for a removeListener in PR #819
=> Fix for #819 caretBounds graphic bug

README.md
Added **Chorus** into 'Who uses RichTextFX?' section
=> Update 'Who uses RichTextFX?'

README.md
[EpubFx](https://gitlab.com/finanzer/epubfx/)
Thanks for your great work
=> Added one more project that uses richtext fx

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
As per https://github.com/FXMisc/RichTextFX/pull/845#issuecomment-524132191
=> Fixed an empty line not being highlighted

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java
=> Added shift backspace to delete backward

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
Fixes [#845](https://github.com/FXMisc/RichTextFX/pull/845#issuecomment-540535109) where if line wrapping is on and the area's width changes then the line highlighter wasn't adjusting.
=> Fixed line highlighter not adjusting to area's width changes

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java, richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java
=> Added methods to recreate or get a paragraph graphic

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
Fixes method spelling mistakes as noted here [#859](https://github.com/FXMisc/RichTextFX/pull/859#issuecomment-548957531) 
Thanks @garybentley
=> Fixed method spelling mistake

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
RFE #864 How to apply style so that subsequent text uses it.
=> Added methods to preset the style of inserted text

richtextfx/src/main/java/org/fxmisc/richtext/InlineCssTextArea.java, richtextfx/src/main/java/org/fxmisc/richtext/StyleClassedTextArea.java
Address #868 Append text with different style.
=> Added convenience API to InlineCss and StyleClassed TextAreas

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
See [#867](https://github.com/FXMisc/RichTextFX/pull/867#issuecomment-557051194)
=> Switched priority of insertionStyle and initialStyle

richtextfx/src/main/java/org/fxmisc/richtext/EditActions.java, richtextfx/src/main/java/org/fxmisc/richtext/InlineCssTextArea.java
=> Moved convenience API from InlineCSSTextArea to EditActions

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/selection/PositionTests.java, richtextfx/src/main/java/org/fxmisc/richtext/CaretSelectionBindImpl.java
Reverts FXMisc/RichTextFX#875 due to having a better alternative solution.
=> Revert "Added test and anchor properties fix"

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java
Addresses [#750](https://github.com/FXMisc/RichTextFX/issues/750#issuecomment-515263663)
=> Skip paragraph graphic creation if index is -1

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
Set a no op undo manager if the parameter is null.
Added javadoc to describe behavior.
=> Added null check to setUndoManager

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
=> Fixed memory leak in ParagraphText

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
Fix regression of #812 due to PR #886
=> Fix regression of 812 due to PR 886

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
Reverts FXMisc/RichTextFX#886 because it included code for virtual flow reuse and not just the memory leak fix.
=> Revert "Fixed memory leak in ParagraphText"

richtextfx/src/integrationTest/java/org/fxmisc/richtext/api/selection/PositionTests.java, richtextfx/src/main/java/org/fxmisc/richtext/SelectionImpl.java
Fixes #906 where it was found that SelectionImpl doesn't honour a range specifies via the constructor.
=> Fixed SelectionImpl not honouring constructor range

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java
=> Fixed focus lost on right click.

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/Indent.java, richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/richtext/ParStyle.java
Relates to #936 paragraph style changes/updates not immediately reflecting.
=> Fix ParStyle equals & indent

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
Fixes #939  Getting exception when trying to get paragraph bounds when caret moves
=> Follow caret fix

richtextfx/src/test/java/org/fxmisc/richtext/model/ReadOnlyStyledDocumentTest.java
=> Added multi paragraph segment test

README.md
Hi there! 
I used RichTextFX in my project SqlBrowserFX which is an sql client.  I would like it to be included in the section 'Who uses RichTextFX?'.
Please let me know if I referenced your work correctly.
Regards
=> Add SqlBrowserFX to README

richtextfx/build.gradle
Bump flowless to 0.6.2 and testfx to 4.0.16
=> Bump flowless and testfx versions

richtextfx/src/integrationTest/java/org/fxmisc/richtext/mouse/ClickAndDragTests.java, richtextfx/src/integrationTest/resources/org/fxmisc/richtext/mouse/padtest.css, richtextfx/src/main/java9/org/fxmisc/richtext/TextFlowExt.java
=> Fix TextFlowExt hit

richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink/Hyperlink.java, richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink/HyperlinkOps.java, richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/hyperlink/TextHyperlinkArea.java
=> Made hyperlinks editable

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
Fixes #1017 where follow caret wasn't updating correctly with large fonts.
=> Follow caret position fix

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
=> Fixed visibleParToAllParIndex parameter check

richtextfx-demos/build.gradle, richtextfx/build.gradle
Also tweaked richtext build.gradle  dependencies for richtext-demo build
=> Bump flowless version

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
=> Added setPlaceholder( Node, Pos )

README.md
Hi!
I use RichTextFX in my project [Boomega](https://github.com/Dansoftowner/Boomega), a book explorer & catalog application.
=> Add Boomega to README

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
=> Fix getCaretBounds exception

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
=> Added showParagraphAtCenter

richtextfx/src/main/java/org/fxmisc/richtext/LineSelection.java
=> Fixed line selection off not updating

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
Fixes #1063 incorrect shape when line spacing is zero and inter-paragraph padding is specified.
Also fixes right hand padding not being honored.
=> Fix selection shape

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
=> InputMethodRequest getTextLocation fix

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java
Fixes #1078 ParagraphBox is not respecting the managed property for the paragraph graphic node
=> Fixed paragraph graphic not managed

richtextfx/src/main/java/org/fxmisc/richtext/MultiChangeBuilder.java
=> Add hasChanges to MultiChangeBuilder

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
Resolves #1082 Line highlighter should not be displayed when selecting
=> Deselect linehighlighter on selection

richtextfx/src/main/java/org/fxmisc/richtext/CodeArea.java
=> fixed code area unicode word selection

richtextfx/src/main/java9/org/fxmisc/richtext/TextFlowLayout.java
Fixes #1137 TextFlow ConcurrentModificationException
=> Fixed TextFlow children concurrency access

richtextfx/build.gradle
=> Prevent pom from containing JavaFX dependencies

richtextfx/src/main/java/org/fxmisc/richtext/InlineCssTextArea.java, richtextfx/src/main/java/org/fxmisc/richtext/StyleClassedTextArea.java
Noticed this missing API while addressing #1150
=> Added isFolded API

build.gradle, richtextfx/build.gradle, richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java, richtextfx/src/main/java/org/fxmisc/richtext/MultiChangeBuilder.java, richtextfx/src/main/java/org/fxmisc/richtext/StyledTextField.java, richtextfx/src/main/java/org/fxmisc/richtext/TextEditingArea.java, richtextfx/src/main/java/org/fxmisc/richtext/model/StyledDocument.java
Fixes #1159 Javadocs fail to build on JDK 17
=> Java doc fixes

build.gradle, richtextfx/build.gradle, richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java, richtextfx/src/main/java/org/fxmisc/richtext/MultiChangeBuilder.java, richtextfx/src/main/java/org/fxmisc/richtext/StyledTextField.java, richtextfx/src/main/java/org/fxmisc/richtext/TextEditingArea.java, richtextfx/src/main/java/org/fxmisc/richtext/model/StyledDocument.java
Doesn't fix the reported issue. 
My bad for misreading the reported errors (didn't see the H1 - H3 conflicts, only the h3 - H3 ones) 
and not actually testing against JDK 17.
=> Revert "Java doc fixes (#1160)"

richtextfx-demos/build.gradle, richtextfx/build.gradle, richtextfx/src/main/java/org/fxmisc/richtext/StyledTextField.java
Fixes #1159 Javadocs fail to build on JDK 17
Thanks to @swpalmer for submitted fix on my reverted PR #1160
=> Java doc fix

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
Fixes #1164 Infinite Loop Problem
where InputMethodRequest getSelectedText recursively calls itself.
=> Fixed InputMethodRequest recursive call

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
Resolves #1210 StyleClassedTextArea + PageUp/PageDown -> NoSuchElementException / IndexOutOfBoundsException
=> Handle NoSuchElement / IndexOutOfBounds exceptions when holding Page Up/Down key

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java, richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledAreaBehavior.java
With this property it is possible to control when user starts overwrite mode using Insert key
=> Add property to area to control overwrite mode (#1224)

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphBox.java
Fixes #1241 Behavior of setParagraphStyle has been changed
This was a regression introduced by #1169
=> Fix minimum paragraph width

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
Resolves #1243 How to show whole text when text area is added to scene
=> Calc auto height on first pass using pref height

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java
=> ParagraphText fix IOOBE

richtextfx/src/main/java/org/fxmisc/richtext/ParagraphText.java, richtextfx/src/main/java/org/fxmisc/richtext/TextExt.java, richtextfx/src/main/java/org/fxmisc/richtext/TextFlowExt.java
Closes #1248 Double underline feature request
=> Double underline

richtextfx/src/main/java/org/fxmisc/richtext/TextFlowLayout.java
Closes #1266 Exception from user moving to next line
=> TextFlowLayout fix IOOB

richtextfx/src/main/java/org/fxmisc/richtext/GenericStyledArea.java
Fixes #1262 SelectionPath is not cleaned form node hierarchy
=> Remove selection cleanup

build.gradle, richtextfx/build.gradle
May address #1264 Build failed: org.openjfx.javafxplugin not found
and also made changes for Gradle 8.5 compatibility.
=> Add gradle plugin portal
